M48
; DRILL file {KiCad 9.0.3} date 2025-10-16T19:59:45+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-16T19:59:45+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
%
G90
G05
T1
X34.916Y-63.546
X34.916Y-100.376
X65.396Y-63.546
X65.396Y-100.376
M30
