M48
; DRILL file {KiCad 9.0.3} date 2025-10-09T23:37:02+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-09T23:37:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.152
%
G90
G05
T1
X150.232Y-81.326
X150.232Y-111.552
X181.474Y-81.326
X181.474Y-111.552
M30
